[project]
name = 'Multidimensional-Ecosystem-Generator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dimensional-parameters]
path = 'contracts/dimensional-parameters.clar'
clarity_version = 2
epoch = 2.5

[contracts.life-forms]
path = 'contracts/life-forms.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
